### ISSUE TITLE
Clone: Dependency collision warning in package.json

### ISSUE THREAD

**Issue by arky** [digidem/osm-p2p-geojson#16]
Not sure if this is intentional. But there seems to duplicate entry for 'clone' package with different versions in dependencies. 

`warning package.json: "dependencies" has dependency "clone" with range "^2.1.0" that collides with a dependency in "devDependencies" of the same name with version "^2.1.1"
`

https://github.com/digidem/osm-p2p-geojson/blob/754161b82361960b44f4baf4ac5726e7cb56f673/package.json#L18

https://github.com/digidem/osm-p2p-geojson/blob/754161b82361960b44f4baf4ac5726e7cb56f673/package.json#L35

**Comment by noffle** [comment]
Fixed in 4.0.3.

**Comment by arky** [comment]
Thanks @noffle I noticed that 'from2' is also imported twice in dependencies.
